sudo apt-get --purge autoremove four-in-a-row -y
sudo apt-get --purge autoremove freeciv -y
sudo apt-get --purge autoremove hitori -y
sudo apt-get --purge autoremove iagno -y
sudo apt-get --purge autoremove hoichess -y
sudo apt-get --purge autoremove lightsoff -y
sudo apt-get --purge autoremove quadrapassel -y
sudo apt-get --purge autoremove swell-foop -y
sudo apt-get --purge autoremove aircrack-ng -y
sudo apt-get --purge autoremove aisleriot -y
sudo apt-get --purge autoremove bind9 -y
sudo apt-get --purge autoremove bind9-host -y
sudo apt-get --purge autoremove zeya -y
sudo apt-get --purge autoremove yaws -y
sudo apt-get --purge autoremove thin -y
sudo apt-get --purge autoremove pdnsd -y
sudo apt-get --purge autoremove dns2tcp -y
sudo apt-get --purge autoremove gdnsd -y
sudo apt-get --purge autoremove ldap2dns -y
sudo apt-get --purge autoremove ophcrack -y
sudo apt-get --purge autoremove nmap -y
sudo apt-get --purge autoremove netris -y
sudo apt-get --purge autoremove maradns -y
sudo apt-get --purge autoremove minetest -y
sudo apt-get --purge autoremove nsd -y
sudo apt-get --purge autoremove nsd3 -y
sudo apt-get --purge autoremove zentyal-dns -y
sudo apt-get --purge autoremove mailutils-imap4d -y
sudo apt-get --purge autoremove dovecot-pop3 -y
sudo apt-get --purge autoremove dovecot-imapd -y
sudo apt-get --purge autoremove cyrus-imapd -y
sudo apt-get --purge autoremove cyrus-pop3 -y
sudo apt-get --purge autoremove sendmail -y
sudo apt-get --purge autoremove postfix -y
sudo apt-get --purge autoremove sqwebmail -y
sudo apt-get --purge autoremove armagetronad -y
sudo apt-get --purge autoremove snmpd -y
sudo apt-get --purge autoremove postgresql -y
sudo apt-get --purge autoremove snmptt -y
sudo apt-get --purge autoremove snmptrapfmt -y
sudo apt-get --purge autoremove audacious -y
sudo apt-get --purge autoremove remmina -y
sudo apt-get --purge autoremove remmina-common -y
sudo apt-get --purge autoremove deluge -y
sudo apt-get --purge autoremove slapd -y
sudo apt-get --purge autoremove iodine -y
sudo apt-get --purge autoremove kismet -y
sudo apt-get --purge autoremove nikto -y
sudo apt-get --purge autoremove john -y
sudo apt-get --purge autoremove medusa -y
sudo apt-get --purge autoremove hydra -y
sudo apt-get --purge autoremove tightvncserver -y
sudo apt-get --purge autoremove fcrackzip -y
sudo apt-get --purge autoremove telnet -y
sudo apt-get --purge autoremove ayttm -y
sudo apt-get --purge autoremove empathy -y
sudo apt-get --purge autoremove logkeys -y
sudo apt-get --purge autoremove p0f -y
sudo apt-get --purge autoremove openarena -y
sudo apt-get --purge autoremove netcat -y
sudo apt-get --purge autoremove netcat-openbsd -y
sudo apt-get --purge autoremove ettercap -y
sudo apt-get --purge autoremove wireshark -y
